# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.django_orm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=256)),
                ('message', models.TextField(default='Dear {patient},\n\nHappy birthday!\n\nSincerely,\n{doctor}')),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('flow', oauth2client.django_orm.FlowField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField(null=True)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drchrono_birthday.Doctor')),
            ],
        ),
    ]
